# Generated by Django 3.1.10 on 2021-07-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='type',
        ),
    ]
