# Generated by Django 3.2.2 on 2021-05-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='count',
            field=models.IntegerField(default=0, max_length=3, verbose_name='加购数量'),
        ),
    ]
